### ISSUE TITLE
Weird 'page level only' error

### ISSUE THREAD

**Issue by thatandromeda** [thatandromeda/locr#3]
```
2021-12-17 11:41:44,845:ERROR:BAD: Failed on http://www.loc.gov/item/2020780940/ with image_url ['https://tile.loc.gov/storage-services/service/rbc/lprbscsm/scsm0270/001q.gif', 'https://tile.loc.gov/storage-services/service/rbc/lprbscsm/scsm0270/001t.gif#h=207&w=150', 'https://tile.loc.gov/storage-services/service/rbc/lprbscsm/scsm0270/001q.gif#h=828&w=600', 'https://tile.loc.gov/storage-services/service/rbc/lprbscsm/scsm0270/001r.jpg#h=8557&w=6198']

Traceback (most recent call last):
  File "/Users/ayelton/Sites/lc_etl/lc_etl/utilities.py", line 212, in slurp
    text = Fetcher(result).full_text()
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/locr/locr.py", line 82, in full_text
    text = handler(self.result).full_text()
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/locr/handlers.py", line 139, in full_text
    response = self._get_text(url)
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/locr/handlers.py", line 102, in _get_text
    return self._http().get(self._request_url(image_path), timeout=TIMEOUT)
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Users/ayelton/.virtualenvs/lc_etl-BGe5voTg/lib/python3.9/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'page level only': No schema supplied. Perhaps you meant http://page level only?
```

Weirdly this may be _correct_, in that when I go to the page for this item and select text from the dropdown, the URL I am given is "https://www.loc.gov/item/2020780940/page%20level%20only".

**Comment by thatandromeda** [comment]
This is actually a pretty common error, e.g.: 

http://www.loc.gov/item/2020778082/
http://www.loc.gov/item/04024223/
http://www.loc.gov/item/2020778103/
http://www.loc.gov/item/2020780940/
